### PR TITLE
Fixed #857 issue

### LINKED ISSUE #857: [Issue] Cache register name validation error
**Describe the bug**
When I clicked create with an empty name field, I got this message error:
image

**To Reproduce**
1. Enable cache registers.
2. POS > Create Cache register
3. Click "Save" without providing any data.

**Expected behavior**
Show the message "Name field is required!" instead of showing the SQL error message.

**Environment:**
 - NexoPOS 4.7.10

### PR DESCRIPTION
**Pull request by MElhalees**
I have fixed this issue, and here's a screen of the results:
image

### CODE REVIEW

**Comment by Blair2004** [comment]
Thank you for your pull request.

**Review by Blair2004 — APPROVED** [review]
Thank you

**Comment by Blair2004** [comment]
Hi,
For upcoming requests, make sure to push on a branch that match the version you would like to apply the fix. The master branch is the final branch where changes from "version" branches are "force-merged".

Concretely, this change should have either be made on v4.6.x, v4.7.x or v4.8.x or on all to apply the fix on each version.

**Comment by MElhalees** [comment]
Okay, I got it, and I am sorry ^_^

**Pull request merged**
